### ISSUE TITLE
single responsibility 

### ISSUE THREAD

**Issue by burritosss** [MrElektronix/Snake#2]
https://github.com/MrElektronix/Snake/blob/a68660abdb8e9fb001fedd63781e98ce39d7a514/Classes/Keyboard.js#L20-L40

Ipv in je keyboard je snake verplaatsen is het beter om in je snake te kijken of er een key wordt gepressed en dan vanuit je snake zichzelf moven

**Comment by MrElektronix** [comment]
Updated

**Comment by burritosss** [comment]
stukken beter zo
