### ISSUE TITLE
Collisions single responsibility 

### ISSUE THREAD

**Issue by burritosss** [MrElektronix/Snake#3]
https://github.com/MrElektronix/Snake/blob/a68660abdb8e9fb001fedd63781e98ce39d7a514/main.js#L45-L55

De collisions van objecten zouden vanuit de objecten zelf moeten gebeuren inplaats van een main file.

Om de vanuit de main file de "death" van de player te kunnen checken zou je ff een event moeten maken.

**Comment by MrElektronix** [comment]
Updated

**Comment by burritosss** [comment]
veel beter, alleen wordt je appel + snake collision wel nog vanuit je main.js gedaan, misschien kan je daar nog iets aan verbeteren.
