### ISSUE TITLE
add listener in update

### ISSUE THREAD

**Issue by burritosss** [MrElektronix/Snake#4]
https://github.com/MrElektronix/Snake/blob/58038b74fe54e96024aac4454dc3fbb89805ecd3/main.js#L40-L48

Je add listener moet buiten de update anders add je de hele tijd een listener aan je eventemitter
en wordt het waarschijnlijk meerdere keren aangeroepen.

waarschijnlijk wordt je EndGame nu even vaak aangeroepen als hoeveel frames je game al bezig is omdat je elke frame een listener toevoegt

**Comment by MrElektronix** [comment]
Updated

**Comment by burritosss** [comment]
gj
