### ISSUE TITLE
Unused code

### ISSUE THREAD

**Issue by burritosss** [MrElektronix/Snake#5]
https://github.com/MrElektronix/Snake/blob/ea45fa626008713b34c8b2a98ca559fe5d4efefc/Classes/Keyboard.js#L5-L8

Deze variable worden nergens gebruikt.

**Comment by burritosss** [comment]
de code is nog steeds niet nodig daar omdat je ze zet in de "start" functie

**Comment by MrElektronix** [comment]
Updated 2
